### PR TITLE
adds a fiat-to-sat and sat-to-fiat calculator to the bot

### PR DESCRIPTION
**Pull request by warioishere**
adds a fiat-to-sat and sat-to-fiat calculator to the bot

let me know what you thing @AE9999

### CODE REVIEW

**Comment by warioishere** [comment]
needed some time and fixing to get this to work haha
be carefull not  to overtake my descriptions of the my fork

**Comment by AE9999** [comment]
Thanks. I will take a look when I have time (somewhere this weekend).

**Comment by warioishere** [comment]
> Thanks. I will take a look when I have time (somewhere this weekend).

sure no problem!

It works, I just needed to edit and adapt multiple times because trial and error to make it work. Thatswhy so many commits.

You can also have a look at my fork, the 3 files mod.rs, business_logic.rs an commands,rs can be just taken, no other stuff in there except your code and the new function. I removed the AS connection stuff, will look at this another time.

**Comment by warioishere** [comment]
conversion-tool-mltb

**Comment by AE9999** [comment]
Some quick git tips. You can actually pretty easy squash commits and override existing branches (as long as there are no merge commits). In your case one should do (in bash):

git rebase --interactive 5cbf0d3e56742f62b269b5514a8435584c378f08

Pick the first (top) commit and change all other 'picks' to 'f' (fold)

Next override the existing branch using:

git push origin master -f

**Comment by warioishere** [comment]
okay sorry I am a git beginner, should I close this PR then? And squash those commits? or will this PR be adapted then?

> Some quick git tips. You can actually pretty easy squash commits and override existing branches (as long as there are no merge commits). In your case one should do (in bash):
> 
> git rebase --interactive [5cbf0d3](https://github.com/AE9999/matrix-lightning-tip-bot/commit/5cbf0d3e56742f62b269b5514a8435584c378f08)
> 
> Pick the first (top) commit and change all other 'picks' to 'f' (fold)
> 
> Next override the existing branch using:
> 
> git push origin master -f

**Comment by AE9999** [comment]
> okay sorry I am a git beginner, should I close this PR then? And squash those commits? or will this PR be adapted then?
> 
> > Some quick git tips. You can actually pretty easy squash commits and override existing branches (as long as there are no merge commits). In your case one should do (in bash):
> > git rebase --interactive [5cbf0d3](https://github.com/AE9999/matrix-lightning-tip-bot/commit/5cbf0d3e56742f62b269b5514a8435584c378f08)
> > Pick the first (top) commit and change all other 'picks' to 'f' (fold)
> > Next override the existing branch using:
> > git push origin master -f

No need to close the request, just perform it and and the mr should update automatically. (just make sure you always keep a local copy of your code in another directory).

**Comment by warioishere** [comment]
I dont know what happened, I did what you said but still there a a lot of commits. and on shell there are no more commits to fold.

Maybe ill just delete my fork and restart a fresh one. Ive save all the code changes locally

**Comment by AE9999** [comment]
No it's fine check https://github.com/AE9999/matrix-lightning-tip-bot/pull/6/files

**Comment by warioishere** [comment]
okay cool, you can check my description for new ideas and also if you like adapt your description which makes installing th bot easier for newbs a bit.

I recognized a crash of the container this night, will check on this if it happends again. Had no time to check logs

**Comment by warioishere** [comment]
@AE9999 thanks for merging, checkout your description and readd your personal details, because my README.md ist different then yours, added my node and my matrixroom 

I am testing the next project on a branch (send2lnadress) and it works without no problems, will make a PR for you today if its okay?

**Comment by AE9999** [comment]
Hi @warioishere I will restore the read.me. Thanks for any future PR I will look at them, but I can't promise it will be before next Saturday / Sunday.

**Comment by warioishere** [comment]
> Hi @warioishere I will restore the read.me. Thanks for any future PR I will look at them, but I can't promise it will be before next Saturday / Sunday.

not much more to add from my side. I added some things that could be useful, and I think the next step, making your bot work as an AS Service is too much for my skills. I would suggest you to try to work on this one next, because it adds a lot to the privacy and security of this project. 

Maybe you can check, how the matrix telegram bridge bot is integrated as a Application Service:

https://github.com/mautrix/telegram

further details on how configuration is done:

https://docs.mau.fi/bridges/python/setup.html?bridge=telegram

also available as docker:

https://docs.mau.fi/bridges/general/docker-setup.html?bridge=telegram

the thing is, the AS Service is a own client that needs a connection that the matrix homeserver can talk to. 
It will then create a real bot that cannot be spied or hacked. 
thats also the way on how to configure on which instances the bot can be used (all matrixservers or just specific ones.

I think this needs a rewrite and reorganisation of your code and how it works currently, and that is defintily too much for me.

Maybe you can check on this project if you ever have time. I'll continue to contribute small things if I see things to optimize :)

**Comment by AE9999** [comment]
Thanks that is precisely the direction I want to go, should have an update in a week or so.

**Comment by warioishere** [comment]
> Thanks that is precisely the direction I want to go, should have an update in a week or so.

sorry the links are not so useful, its a python bases bridge, I just wanted to show an example, maybe the config files of this may help you more:

https://github.com/mautrix/telegram/blob/master/mautrix_telegram/example-config.yaml

then they mostly have some tools that turn the configuration file of the Service into a `registration.yaml` that needs to be placed in the directory of your homeserver and then it needs to be activated in the homeserver.yaml:

```
app_service_config_files:
  - /etc/matrix-synapse/double_puppet.yaml
  - /etc/matrix-synapse/mautrix-telegram-bot.yaml
```

and here general instructions from matrix:

https://www.matrix.org/blog/2015/03/02/introduction-to-application-services/

Hope I gave you a small idea!

greetings!

**Pull request merged**
